services:
  server:
    build: backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  client-mobile:
    build: mobile/
    volumes:  
      - app-volumes:/app/build/app/outputs/flutter-apk:rw
    tty: true
  client_web:
    build: web/
    depends_on:
      - server
      - client-mobile
    ports:
      - "8081:8081"
    volumes:
      - ./web/src:/app/src
      - app-volumes:/app/public:ro
volumes:
  app-volumes:
