# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AREA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  NODE_VERSION: 18

jobs:
  build-backend:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: Yarn Setup
    # You may pin to the exact commit or the version.
    # uses: DerYeger/yarn-setup-action@f55be5383ea94f5eb25b20aee609af4603a68dde
      uses: DerYeger/yarn-setup-action@v1.0.1
      with:
      # The version of Node.js that will be used
        node-version: ${{ env.NODE_VERSION }}
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - name: Dependencies installation
      run: yarn
    - name: Build TypeScript
      run: yarn run build
    - name: Running tests
      run: yarn test
  
  build-container-backend:
    
    runs-on: ubuntu-latest
    
    container: node:18
    
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies installation
        run: yarn
      - name: Build TypeScript
        run: yarn run build
      - name: Running tests
        run: yarn test
